require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rubygems'
require 'hoe'
require 'rake/testtask'
require 'rake/rdoctask'
require 'tasks/rails'

Hoe.new('sample_rails', '1.0.0') do |p|
  p.readme_file = 'README.rdoc'
  p.extra_deps << ["rails", "~> 2.3.2"]
  p.extra_deps << ["harker", "~> 0.0.1"]
  p.developer('Phil Hagelberg', 'technomancy@gmail.com')
end
